namespace: my-namespace

nginx:
  name: nginx
  replicas: 1
  image: marykravetss/my-nginx:latest
  configMapName: nginx-configmap

apache:
  name: apache
  replicas: 1
  image: marykravetss/my-apache:latest

#myTlsSecret:
#  name: my-tls-secret
#  tlsCrt: |-
#    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUrekNDQStPZ0F3SUJBZ0lTQkx1RDZ2QTR6
#    aGJ3Q0daOU1HTUFDbzJLTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURNeEN6QUpCZ05WQkFZVEFsVlRN
#    Ull3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rd3dDZ1lEVlFRRApFd05TTVRBd0hoY05N
#    alF4TURFME1UazBOREkwV2hjTk1qVXdNVEV5TVRrME5ESXpXakFoTVI4d0hRWURWUVFECkV4WnRl
#    WFJsYzNSb2IzTjBNVEV1YUc5d2RHOHViM0puTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FR
#    OEEKTUlJQkNnS0NBUUVBNVFhN2l1SzNGMEVoaHo0ampZTTdTYVRIa1VKd1FGdElsZWZaRWpnOFdQ
#    VGRxamhVbkFSTwpkbkg2dWkya0piMVAyeGhoSmV1R1hOdnVza0xTdFhrQThwTG9ieGt3TldKNjdt
#    YXd3Wkc5Sk0zeUc3Wkx5aFZUCmh5V1VQV2RJNzFEYVRnYnFBWWtvK3ZHMmJRdjZiRGpIUkQ0REtT
#    L2hrTmdTdnZQY3FXL3E1Q3h5d3NMVEVkUGcKRk1RNkRKRWF6RzV3QmZnaVJWVStQQlJhM3lFRG93
#    VkpBd3IwMm1kOUE4ZnMvU2x4N20zREFyNGhHWkwzTm5IRQp2N1FQS2ZuQThSVGY2VkxpUjhiTnQy
#    WVZXL200UFd1SWU3Wmg2WTJoYStLOURpWTNvWkhGV2RJcGUvYXdZVTg2CjhZem82ZHp1VHpTVzhF
#    S05HR2NaN1IxbDdDc0ZwOUtmaVFJREFRQUJvNElDR1RDQ0FoVXdEZ1lEVlIwUEFRSC8KQkFRREFn
#    V2dNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4
#    RQpBakFBTUIwR0ExVWREZ1FXQkJTTUZlZEtCM1pLTGM5NnZERUhUWVlkcDNBMGhEQWZCZ05WSFNN
#    RUdEQVdnQlM3CnZNTkhwZVM4cWNiRHBISU1FSTJpTmVISTZEQlhCZ2dyQmdFRkJRY0JBUVJMTUVr
#    d0lnWUlLd1lCQlFVSE1BR0cKRm1oMGRIQTZMeTl5TVRBdWJ5NXNaVzVqY2k1dmNtY3dJd1lJS3dZ
#    QkJRVUhNQUtHRjJoMGRIQTZMeTl5TVRBdQphUzVzWlc1amNpNXZjbWN2TUNFR0ExVWRFUVFhTUJp
#    Q0ZtMTVkR1Z6ZEdodmMzUXhNUzVvYjNCMGJ5NXZjbWN3CkV3WURWUjBnQkF3d0NqQUlCZ1puZ1F3
#    QkFnRXdnZ0VEQmdvckJnRUVBZFo1QWdRQ0JJSDBCSUh4QU84QWRnRGcKa3JQOERCM0k1MmcySDk1
#    aHVaWk5DbEo0R1lweTFuTEVzRTJsYlc5VUJBQUFBWktNeFFRbkFBQUVBd0JITUVVQwpJUUNZWFlQ
#    eFlCMDl0Z1hEMXE1ZlZSWVk1NUI5QVI2VVY0Mmp2dmUrdjlGVkZ3SWdhVVp2NEt6aFQ5cGZkN2tC
#    CmFOK3NhMW8xM05nZ0JDUFNTMEhmS2k4cVY4VUFkUURtMGpGalFIZU13UkJCQnRkeHVjN0Iwa0Qy
#    bG9TRys3cUgKTWgzOUhqZU9VQUFBQVpLTXhRU1ZBQUFFQXdCR01FUUNJR1pST2xseFoya3RLY2Qv
#    R0hJcHZBL2t2TzlVT01nYQpUR0Z3N0N0RXRUSlFBaUJDYmswaitTL2RQS1RZMUw1OHJGdnhaY3Jh
#    VU0yeDRURytrVUpsUGpNSDFqQU5CZ2txCmhraUc5dzBCQVFzRkFBT0NBUUVBZXV6YS9WNlI5Wm1K
#    ZE1WaWlBR3ZQTlZ6TWxaS25zRE1kL1lxVHdycXhRVlkKV04yZ3lIVTlJY29SS2VGT3dIS3o0N1B4
#    c0tZaUNQOSt1Z1RtczIzZng4RHNUWGxabUdlVCt6cmsya29pYTBjQwpEMXFqdFJCMTNveWZEQkRC
#    STI2QmVxUDNaTDhmVkRyRUkvNzFKR1NkUk1MdFJTdjN6T0FTbERLMlMxbllSazhVCnljVWRXSlJK
#    bDg4MWhiZ3oyMW9UdnJ2Wko1eUhWSmRGUGljbWYvaDJrL1pLQW9TL2VzbjV0OWhTSHlSYjlPS3EK
#    K280R2lTTThqcGpvcXlza1FGZm9rMFFmdUp0S29TTGZIWi9SWWdyWmEyczl1ckdwN2dDM3VBVEI4
#    T1NOSkNLbAo1aC9GNTE2dXhCL09rNHpiOG05dGV6MWJqamphRHo1TWwvQTZkd0Vvc1E9PQotLS0t
#    LUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlGQlRD
#    Q0F1MmdBd0lCQWdJUVM2aFNrL2VhTDZKekJrdW9CSTExMERBTkJna3Foa2lHOXcwQkFRc0ZBREJQ
#    Ck1Rc3dDUVlEVlFRR0V3SlZVekVwTUNjR0ExVUVDaE1nU1c1MFpYSnVaWFFnVTJWamRYSnBkSGtn
#    VW1WelpXRnkKWTJnZ1IzSnZkWEF4RlRBVEJnTlZCQU1UREVsVFVrY2dVbTl2ZENCWU1UQWVGdzB5
#    TkRBek1UTXdNREF3TURCYQpGdzB5TnpBek1USXlNelU1TlRsYU1ETXhDekFKQmdOVkJBWVRBbFZU
#    TVJZd0ZBWURWUVFLRXcxTVpYUW5jeUJGCmJtTnllWEIwTVF3d0NnWURWUVFERXdOU01UQXdnZ0Vp
#    TUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRRFBWK1hteEZRUzdiUkgvc2tu
#    V0haR1VDaU1IVDZJM3dXZDFiVVlLYjNkdFZxLyt2Yk9vNzZ2QUNGTApZbHBhUEFFdnhWZ0Q5b24v
#    amhGRDY4RzE0QlFIbG85dkg5Zm51b0U1Q1hWbHQ4S3ZHRnMzSmlqbm8vUUhLMjBhCi82dFl2Sld1
#    UVAvcHkxZkV0VnQvZUEwWVlid1g1MVRHdTBtUnpXNFkwWUNGN3FabE5yeDA2cnhRVE9yOElmTTQK
#    RnBPVXVyRFRhemdHelJZU2VzcFNkY2l0ZHJMQ25GMllSVnh2WVh2R0xlNDhFMUtHQWRsWDVqZ2Mz
#    NDIxSDVLUgptdWRLSE14RnFISlY4TERtb3dmcy9hY2JacDQvU0l0eGhIRll5VHI2NzE3eVcwUXJQ
#    SFRuajdKSHdRZHF6WnEzCkRaYjNFb0VtVVZRSzdHSDI5L1hpOG9ySWxRMk5BZ01CQUFHamdmZ3dn
#    ZlV3RGdZRFZSMFBBUUgvQkFRREFnR0cKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQ0JnZ3JC
#    Z0VGQlFjREFUQVNCZ05WSFJNQkFmOEVDREFHQVFILwpBZ0VBTUIwR0ExVWREZ1FXQkJTN3ZNTkhw
#    ZVM4cWNiRHBISU1FSTJpTmVISTZEQWZCZ05WSFNNRUdEQVdnQlI1CnRGbm1lN2JsNUFGemdBaUl5
#    QnBZOXVtYmJqQXlCZ2dyQmdFRkJRY0JBUVFtTUNRd0lnWUlLd1lCQlFVSE1BS0cKRm1oMGRIQTZM
#    eTk0TVM1cExteGxibU55TG05eVp5OHdFd1lEVlIwZ0JBd3dDakFJQmdabmdRd0JBZ0V3SndZRApW
#    UjBmQkNBd0hqQWNvQnFnR0lZV2FIUjBjRG92TDNneExtTXViR1Z1WTNJdWIzSm5MekFOQmdrcWhr
#    aUc5dzBCCkFRc0ZBQU9DQWdFQWtySG5RVGZyZVoyQjVzM2lKZUU2SU9tUVJKV2pnVnpQdzEzOXZh
#    QncxYkdXS0NJTDB2SW8Kend6bjFPWkRqQ1FpSGNGQ2t0RUpyNTlMOU1od1R5QVdzVnJkQWZZZitC
#    OWhheFFuc0hLTlk2N3U0czVMenpmZAp1NlBVemVldFVLMjl2K1BzUG1JMmNKa3hwK2lOM2VwaTRo
#    S3U5WnpVUFN3TXF0Q2NlYjdxUFZ4RWJwWXhZMXA5CjFuNVBKS0JMQlg5ZWI5TFU2bDh6U3hQV1Y3
#    YkszbEc0WGFNSmduVDl4M2llczdtc0Z0cEtLNWJEdG90aWovbDAKR2FLZUE5N3BiNXV3RDlLZ1d2
#    YUZYTUlFdDhqVlRqTEV2d1JkdkNuMjk0R1BERjA4VThsQWtJdjd0Z2hsdWFRaAoxUW5sRTRTRU40
#    TE9FQ2o4ZHNJR0pYcEdVazNhVTNLa0p6OWljS3krYVVnQSsyY1AyMXVoNk5jRElTM1h5ZmFaClFq
#    bURROTkzQ2hJSThTWFd1cFFaVkJpSXBjV080UnFaazNscjdCejVNVUN3ekRJQTM1OWU1N1NTcTVD
#    Q2tZME4KNEI2VnVsazdMa3Rmd3JkR05WSTVCc0M5cXF4U3dTS2dSSmVaOXd5Z0lhZWhiSEZIRmhj
#    QmFNREtwaVpsQkh5egpyc25ubEZYQ2I1czhIS241THNVZ0d2QjI0TDdzR05aUDJDWDdkaEhvditZ
#    aEQram96TFcycDlXNDk1OUJ6MkVpClJtcUR0bWlYTG56cVRwWGJJK3N1eUNzb2hLUmc2VW4wUkM0
#    NytjcGlWd0hpWFpBVytjbjhlaU5JanFiVmdYTHgKS1BwZHp2dnRUbk9QbEM3U1FaU1ltZHVucjNC
#    ZjliNzdBaUMvWmlkc3RLMzZkUklMS3o3T0E1ND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
#  tlsKey: |-
#    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
#    QVNDQktZd2dnU2lBZ0VBQW9JQkFRRGxCcnVLNHJjWFFTR0gKUGlPTmd6dEpwTWVSUW5CQVcwaVY1
#    OWtTT0R4WTlOMnFPRlNjQkU1MmNmcTZMYVFsdlUvYkdHRWw2NFpjMis2eQpRdEsxZVFEeWt1aHZH
#    VEExWW5ydVpyREJrYjBremZJYnRrdktGVk9ISlpROVowanZVTnBPQnVvQmlTajY4Ylp0CkMvcHNP
#    TWRFUGdNcEwrR1EyQksrODl5cGIrcmtMSExDd3RNUjArQVV4RG9Na1JyTWJuQUYrQ0pGVlQ0OEZG
#    cmYKSVFPakJVa0RDdlRhWjMwRHgrejlLWEh1YmNNQ3ZpRVprdmMyY2NTL3RBOHArY0R4Rk4vcFV1
#    Skh4czIzWmhWYgorYmc5YTRoN3RtSHBqYUZyNHIwT0pqZWhrY1ZaMGlsNzlyQmhUenJ4ak9qcDNP
#    NVBOSmJ3UW8wWVp4bnRIV1hzCkt3V24wcCtKQWdNQkFBRUNnZ0VBSDlVWXVnd2E4S04vMm9GYmhh
#    N0l6Y3FXWm0wNmx1ZFpKbVRNT2drUThqaE8KbXZzclgyZ0YwOWF4eDdEU1VPQ0lPZWFna2hteldq
#    TERjWWx5S2dFQWpiYTNrY0dKZnRJS1RocDkxTm5CMVZ5KwptdlZ5Z1VzSGloQkNFMnJJcTJLc2hR
#    M1c5cEd1M1hvOUpkajFYSmRqc3V0L212anB2QzBjSmVoVk1rTzQvUytoCkR5ckNlYUZrWG1rWEhB
#    T2VxaExUNDVvYXFqUTBNeW00OXBvUFFzbjlicXlCUFlLd1F6b0YzL2Ixd2hNV3JyNXYKUVZkUE5Z
#    U3JxVmptQXhpdW1UVWlUeVZOWk8xNWtJQnVCMnZ3NHh6NTZDRGo4MHhtbWdJelBybnI2M0lUTkF0
#    cApQTFJaZXFORmQ2ZlROZVlRT0orcmYrRGVvR3Z5WnZaUkVnVzFzamhCbFFLQmdRRHZacHArTHJT
#    MUl0d0JqeFBwCi9aNU5PL3BVRFRRcE1ucWZYVW16dS9TTnBFTzlEeTV6UytueWtNSDlaeGd6TWtv
#    bVh1L3ZBUm43ZHBNRkhjaXIKTDZxSnFHa3JpTnBBRWpqQ2xKT1B5NnhBWVR3dWRWd0Z5eDV6UitW
#    Um5WWStkbGVtUW5BRENzWFIrSXJVZWlDVgpzU1d5ZTloYURRalZqMm96OUU0TjRZNzZxd0tCZ1FE
#    MDUvcjdUdjBwYnRFYXdNNU8zQmVwYkc3amlxVi9TZWVpCkpmQ3FkVXNEZDNTUTk3YXJaMEd3U1Fh
#    V2x2NFVvNG9ZNjB3WE9JV2xwakdxc001T3lDUEgrNTZGTVIxVUFTSTgKUlk4Z0F2Yjd2ZUZRQjhs
#    WU9SRjdvaFF4NHlCR25IaHN5MTZtMktwbXVmWmtiYTBxcGQvSldOV1pWY1dOOGUzRApYb0ZpZGFL
#    T213S0JnQ3NQZllKc3pEdzRoUElTMWpZa1ZERDROTktoZlZ4YnBBcStNTitQVXpHVzlrZ3ZUdCtX
#    CkxBSmhYME5CSSsweGduemNYclBTc3VXME1rV2RVZGJZd0FmNnJ0QVIwWS9zdHlEb3NKSVF4Rzdn
#    RG44Y3hPeVYKMkdoTDZrZC8wVjl5MGRrcDRoUHFBQ01BWFpoU1QwSWRsdlkvcUc2cUlZaW9QeVlS
#    TDJqM3hVdjVBb0dBYlNJQwp3WUlOWmkwdm1SQlozdUpNMlA2czIxQ3BOdk9qK0ttWGVSNFRjMVFE
#    NmFXNURPQlNjVS9aVTdtdE4xMDQ2S25SCm1uZGhkdE44Um1mTFIyZ0FLZG1DWmkvZ3RkSmJneWdz
#    QTBQTzg1ZEZrL2drVE9BQlhtcDNQVlBNeWlwbnIzTmcKbGxEdWZpQllINkNRRGZVa3FBQ2lEbFll
#    Vm9aOFFSY1g2TndxdUFrQ2dZQlhLK1k0Vlc3VVQ5ZTJLK2JwV2tQeApZVTFwLzVuNDBpdkJaTmhF
#    KzJIQ21WRGFZS2p4c2ZqajhIcks4UzI2K1FSZHdFWG5ZVlBnMmFRNDdPb0p6a3E4CmQ3N0VESHdC
#    eTNNMWt1d3JGSHZCY2lWTXlzYTlUVElVd3R4U1FsdjVpdGQ0L2xudWlsN2F1R2xocjF2VWk0U3AK
#    cFNETnd3aFV3NjkxMkF1cXU0cFVYdz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

nginxConfigmap:
  nginxConf: |-
    server {
        listen 80;
        listen 443 ssl;
        ssl_certificate /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/privkey.pem;
        server_name mytesthost11.hopto.org;
        location / {
            root /var/www/html;
            index index.html;
        }
        location /secondpage {
            alias /var/www/html;
            index secondpage.html;
        }
        location /music {
            alias /var/www/html/music/file.mp3;
            add_header Content-Disposition 'attachment; filename="file.mp3"';
        }
        location /info.php {
            proxy_pass http://apache-service:8080/info.php;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /secondserver {
            return 301 https://onliner.by$request_uri;
        }
    }
