apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apache.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.apache.name }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
