apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.myTlsSecret.name | default "my-tls-secret" }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.myTlsSecret.tlsCrt | quote }}
  tls.key: {{ .Values.myTlsSecret.tlsKey | quote }}
